// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: common/proto/handlers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Barcode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Barcode) Reset() {
	*x = Barcode{}
	mi := &file_common_proto_handlers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Barcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barcode) ProtoMessage() {}

func (x *Barcode) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_handlers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barcode.ProtoReflect.Descriptor instead.
func (*Barcode) Descriptor() ([]byte, []int) {
	return file_common_proto_handlers_proto_rawDescGZIP(), []int{0}
}

func (x *Barcode) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Barcode       string                 `protobuf:"bytes,3,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_common_proto_handlers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_handlers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_common_proto_handlers_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_common_proto_handlers_proto protoreflect.FileDescriptor

const file_common_proto_handlers_proto_rawDesc = "" +
	"\n" +
	"\x1bcommon/proto/handlers.proto\x12\bhandlers\"#\n" +
	"\aBarcode\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"c\n" +
	"\aProduct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x18\n" +
	"\abarcode\x18\x03 \x01(\tR\abarcode\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count2N\n" +
	"\x0fHandlersService\x12;\n" +
	"\x13GetProductByBarcode\x12\x11.handlers.Barcode\x1a\x11.handlers.ProductB4Z2github.com/AliNajafi/vvm_server/common/proto;protob\x06proto3"

var (
	file_common_proto_handlers_proto_rawDescOnce sync.Once
	file_common_proto_handlers_proto_rawDescData []byte
)

func file_common_proto_handlers_proto_rawDescGZIP() []byte {
	file_common_proto_handlers_proto_rawDescOnce.Do(func() {
		file_common_proto_handlers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_handlers_proto_rawDesc), len(file_common_proto_handlers_proto_rawDesc)))
	})
	return file_common_proto_handlers_proto_rawDescData
}

var file_common_proto_handlers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_handlers_proto_goTypes = []any{
	(*Barcode)(nil), // 0: handlers.Barcode
	(*Product)(nil), // 1: handlers.Product
}
var file_common_proto_handlers_proto_depIdxs = []int32{
	0, // 0: handlers.HandlersService.GetProductByBarcode:input_type -> handlers.Barcode
	1, // 1: handlers.HandlersService.GetProductByBarcode:output_type -> handlers.Product
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_handlers_proto_init() }
func file_common_proto_handlers_proto_init() {
	if File_common_proto_handlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_handlers_proto_rawDesc), len(file_common_proto_handlers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_handlers_proto_goTypes,
		DependencyIndexes: file_common_proto_handlers_proto_depIdxs,
		MessageInfos:      file_common_proto_handlers_proto_msgTypes,
	}.Build()
	File_common_proto_handlers_proto = out.File
	file_common_proto_handlers_proto_goTypes = nil
	file_common_proto_handlers_proto_depIdxs = nil
}
